apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-install-config
  namespace: {{ .Values.clusterName }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.clusterName }}-install-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        ssh-privatekey: |
          {{ "{{ .ssh_private_key }}" }}
        install-config.yaml: |
          apiVersion: v1
          baseDomain: {{ .Values.baseDomain }}
          metadata:
            name: {{ .Values.clusterName }}
          controlPlane:
            hyperthreading: Enabled
            name: master
            replicas: {{ .Values.controlPlaneReplicas }}
            platform:
              vsphere:
                cpus: {{ .Values.vsphere.controlPlane.cpus }}
                coresPerSocket: {{ .Values.vsphere.controlPlane.coresPerSocket }}
                memoryMB: {{ .Values.vsphere.controlPlane.memoryMB }}
          compute:
          - hyperthreading: Enabled
            name: worker
            replicas: {{ .Values.workerReplicas }}
            platform:
              vsphere:
                cpus: {{ .Values.vsphere.workers.cpus }}
                coresPerSocket: {{ .Values.vsphere.workers.coresPerSocket }}
                memoryMB: {{ .Values.vsphere.workers.memoryMB }}
          platform:
            vsphere:
              vCenter: {{ .Values.vsphere.vcenter }}
              username: "{{ "{{ .vcenter_user }}" }}"
              password: "{{ "{{ .vcenter_password }}" }}"
              datacenter: {{ .Values.vsphere.datacenter }}
              defaultDatastore: {{ .Values.vsphere.datastore }}
              cluster: {{ .Values.vsphere.cluster }}
              network: {{ .Values.vsphere.network }}
              apiVIPs:
              - {{ .Values.vsphere.apiVIP }}
              ingressVIPs:
              - {{ .Values.vsphere.ingressVIP }}
          pullSecret: '{{ "{{ .pull_secret }}" }}'
          sshKey: |
            {{ "{{ .ssh_public_key }}" }}
  data:
    - secretKey: vcenter_user
      remoteRef:
        key: {{ .Values.secretStore.path }}
        property: username
    - secretKey: vcenter_password
      remoteRef:
        key: {{ .Values.secretStore.path }}
        property: password
    - secretKey: pull_secret
      remoteRef:
        key: {{ .Values.secretStore.path }}
        property: pullSecret
    - secretKey: ssh_private_key
      remoteRef:
        key: {{ .Values.secretStore.path }}
        property: sshPrivateKey
    - secretKey: ssh_public_key
      remoteRef:
        key: {{ .Values.secretStore.path }}
        property: sshPublicKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-pull-secret
  namespace: {{ .Values.clusterName }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.clusterName }}-pull-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ "{{ .pull_secret }}" }}'
  data:
    - secretKey: pull_secret
      remoteRef:
        key: {{ .Values.secretStore.path }}
        property: pullSecret