apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
spec:
  clusterName: {{ .Values.clusterName }}
  clusterNamespace: {{ .Values.clusterName }}
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true