apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
    cloud: vsphere
    vendor: OpenShift
    environment: {{ .Values.environment }}
spec:
  hubAcceptsClient: true